version: '3'

volumes:
  postgres_data:

services:
  app: 
    build: 
      context: ./shopping_list_back
      dockerfile: ./dockerfile
    hostname: app
    restart: always
    ports:
      - 3001:3001
    depends_on:
      - db

  db:
    image: postgres:latest
    hostname: db
    restart: always
    env_file:
      - .db.env
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - POSTGRES_DB=db
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data