version: '3'

volumes:
  postgres_data:

services:
  db:
    image: postgres:latest
    hostname: db
    restart: always
    env_file:
      - .db.env
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - POSTGRES_DB=db
    ports:
      - 5432:5432
    volumes:
      - ./shopping_list_data_base/:/docker-entrypoint-initdb.d/
      - postgres_data:/var/lib/postgresql/data