export enum DatabaseDiTokens {
  DATA_SOURCE = 'DATA_SOURCE',
  MERCHANT_REPOSITORY = 'MERCHANT_REPOSITORY',
  MERCHANT_OWNER_REPOSITORY = 'MERCHANT_OWNER_REPOSITORY',
  AISLE_REPOSITORY = 'AISLE_REPOSITORY',
  PRODUCT_CATEGORY_REPOSITORY = 'PRODUCT_CATEGORY_REPOSITORY',
}
